POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "test12@test.com",
    "password": "test12"
}
###
POST http://localhost:3000/api/v1/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "test@test.com",
    "company_name": "crart_Company",
    "password": "test"
}

###
POST http://localhost:3000/api/v1/invoices/create
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJjb21wYW55X25hbWUiOiJjcmFydF9Db21wYW55In0sImlhdCI6MTYzNTIyMzc2OCwiZXhwIjoxNjM1MzEwMTY4fQ.e75WXaqUnNlCtCkS8HQqnlHYrardguNojbUXwU9wnn0

{
    "name": "5th post",
    "user_id": 2,
    "names": ["milk", "sandwich"],
    "prices": [20, 15]
}

###
